name: Contract Test

on:
  push:
    branches:
      - main
      - develop
      - feature/**
      - chore/**
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          # Pin to a predictable Node 18.x LTS version compatible with Hardhat
          node-version: "18.17.1"

      - name: Install dependencies
        run: npm ci

      - name: Compile contracts (Hardhat)
        run: npx hardhat compile

      - name: Run contract tests (Hardhat + TypeScript)
        run: npx hardhat test
